import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@/components/next-theme-provider";
import NavHeader from "@/components/nav-header";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarComp from "@/components/sidebar";
import SocialListComp from "@/components/social-list";
import { getCookie } from "@/app/actions";
import { UserAuth } from "@/types/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userCookie = await getCookie("user");
  const user = userCookie ? (JSON.parse(userCookie.value) as UserAuth) : null;

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <SidebarComp></SidebarComp>
            <main className="w-full bg-gradient-to-b from-neutral-50 dark:from-neutral-900 to-secondary relative">
              {/* nav-header */}
              <NavHeader user={user} />
              {/* <SidebarTrigger /> */}
              <div className="w-full h-full overflow-y-auto">{children}</div>
              <SocialListComp></SocialListComp>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
